name: Deploy Pages

on:
  push:
    branches:
     - 'master'

jobs:

  deploy:
    name: 'Deploy to Pages'
    runs-on: 'ubuntu-latest'

    steps:

    - name: 'Setup Node'
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: Login to GPR
      uses: jgierer12/npm-auth-gpr@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Install Dependencies'
      run: npm install

    - name: 'Build Static Content'
      run: npm run build
      env:
        SNIPPETS_ENDPOINT: "https://snippets.ranna.dev"
        RANNA_APP_LOCATION: "https://app.ranna.dev"
        LANGUAGES_ENDPOINT: "https://languages.ranna.dev/languages.minified.json"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: app.snippets.ranna.dev